name: Lint

on:
  workflow_dispatch:
  push:
    paths:
      - "**.py"
      - "pyproject.toml"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python3 -m pip install ruff~=0.1.11

      - name: Ruff
        run: ruff check src tests
